### ISSUE TITLE
Create multiple PRs based on feature branches

### ISSUE THREAD

**Issue by arctouch-herculescunha** [shayki5/azure-devops-create-pr-task#1]
I need to keep all feature branches updated with development.
Is it possible to use it in order to open a pull request for each feature branch with source branch being development?

feature branch mask: feature/*

**Comment by shayki5** [comment]
Hi,
Currently, you can add the task multiple times for each feature branch.
Do you want to merge development to feature branches or vice versa? 
I will try to add it soon.

**Comment by herculesjr** [comment]
Hi! 
The idea was to avoid adding a task to every feature branch that I have since this will need a lot of maintenance on the yaml file. 

My goal is to add something: 
```
- task: CreatePullRequest@1
  inputs:
    sourceBranch: 'development'
    targetBranch: 'feature/*'
    **multipleTargets: true**
    title: 'Test'
  env:
     System_AccessToken: $(System.AccessToken)
```
