### ISSUE TITLE
Validation Fails

### ISSUE THREAD

**Issue by RigottiG** [shayki5/azure-devops-create-pr-task#121]
I'm trying to create a pull request by Azure Pipelines but always came across w the following error

```

{"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}
```

My yaml file

```
  - task: CreatePullRequest@1
    inputs:
      repoType: 'GitHub'
      githubEndpoint: 'RigottiG'
      githubRepository: 'RigottiG/myRepository'
      sourceBranch: 'ci/pipeline-a'
      targetBranch: 'ci/pipeline-b'
      title: 'a -> b'
      description: 'update a w b'
```

**Comment by shayki5** [comment]
Hi!
Can you run it with `system.debug` = `true` and share here the logs please?

**Comment by shayki5** [comment]
@RigottiG ping :)

**Comment by Qstick** [comment]
Getting same error

```
{"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}
```

```
      - task: CreatePullRequest@1
        displayName: PR Change to Github
        inputs:
          repoType: 'GitHub'
          githubEndpoint: 'github release'
          githubRepository: '$(Build.Repository.Name)'
          sourceBranch: 'api-docs'
          targetBranch: 'develop'
          title: 'Update API Docs'
```

Debug log
https://dev.azure.com/Prowlarr/Prowlarr/_build/results?buildId=1312&view=logs&j=647575bd-7b0a-5c05-4cec-6220aff6e020&t=55c95463-c0e1-546a-4d6e-efe51616e6df
