### ISSUE TITLE
Automatically complete PR

### ISSUE THREAD

**Issue by maasha** [shayki5/azure-devops-create-pr-task#169]
For some reason, the below pipeline fails to automatically complete the generated PR (the generated PR can be completed manually, just fine). How can automatic PR completion be achieved?

```
trigger:
    - develop

pool:
    vmImage: windows-latest

steps:
    - task: CreatePullRequest@1
      displayName: 'Create PR: develop > master'
      continueOnError: false
      inputs:
          autoComplete: true
          bypassPolicy: true
          commitMessage: 'Auto-merge: develop > master'
          repoType: 'Azure DevOps'
          repositorySelector: 'currentBuild'
          sourceBranch: 'develop'
          targetBranch: 'master'
          title: 'Auto-merge: develop > master'
```
