### ISSUE TITLE
Unicode-Character in Title isn't used correct in Azure DevOps

### ISSUE THREAD

**Issue by MartinDemberger** [shayki5/azure-devops-create-pr-task#36]
I added the unicode character 🔀 as first symbol of the title but it isn't printed correctly in Azure DevOps.

I create the Pull-Request with
```yaml
  - task: CreatePullRequest@1
    inputs:
      repoType: 'Azure DevOps'
      sourceBranch: '$(Build.SourceBranch)'
      targetBranch: 'userstories/*'
      title: '🔀 Automatic Merge from master'
      linkWorkItems: false
      autoComplete: true
    env:
      System_AccessToken: $(System.AccessToken)
```
 The symbol is printed in the pull-request as `??`.

I also tried
```yaml
  - task: CreatePullRequest@1
    inputs:
      repoType: 'Azure DevOps'
      sourceBranch: '$(Build.SourceBranch)'
      targetBranch: 'userstories/*'
      title: '&#128256; Automatic Merge from master'
      linkWorkItems: false
      autoComplete: true
    env:
      System_AccessToken: $(System.AccessToken)
```
But this leads to a pull request `&#128256; Automatic Merge from master`

I'm able to change the title in DevOps to the Unicode which is rendered correctly.

How can I use this Unicode in the title?
