### ISSUE TITLE
Not working for github PRs

### ISSUE THREAD

**Issue by prma85** [shayki5/azure-devops-create-pr-task#38]
Hey, I like the idea of this task, but it is not working for me

```yml
steps:
- task: ShaykiAbramczyk.CreatePullRequest.CreatePullRequest.CreatePullRequest@1
  displayName: 'Create Pull Request'
  inputs:
    repoType: GitHub
    githubEndpoint: 'GitHub-iQmetrixService'
    sourceBranch: 'automated-update-storybook'
    targetBranch: master
    title: '[Azure Pipelines] Automated Update for Storybook'
    description: 'Minor version bump'
```

When using it, I am getting the error:
`You cannot call a method on a null-valued expression.`
